### ISSUE TITLE
Could you please add support for vs2019?

### ISSUE THREAD

**Issue by ameaninglessname** [reloZid/vs-filtersync#4]

**Comment by mjaun** [comment]
Please see #3. Leaving this issue open in case someone else wants to work on it.

**Comment by LukeBorowy** [comment]
Done in my fork #5

**Comment by mjaun** [comment]
Thanks, @BakedPotato03 
Created a new release with the built binary: https://github.com/reloZid/vc-fileutils/releases/tag/v1.4
